\documentclass{article}

\usepackage{multicol}
\usepackage{geometry}
\usepackage{amsmath}

\geometry{
 a4paper,
 total={210mm,297mm},
 left=20mm,
 right=20mm,
 top=20mm,
 bottom=20mm,
 }

\begin{document}

\title{Analysis Report\\-\\
        Rainet project}
\author{Diogo Ribeiro, Lionel Spinelli, Andreas Zanzoni, Christine Brun}
\maketitle

\section{Introduction} 

TODO

\section{Parameters used}

<<parameters_log, fig.keep="all", echo=FALSE, message=F, warning=F>>=
  source( paste( working_dir, "parameters_log.R", sep="/"))
@

\section{RNA numbers report}

<<rna_numbers, fig.keep="all", echo=FALSE, message=F, warning=F>>=
  source( paste( working_dir, "rna_numbers.R", sep="/"))
@

\section{Expression report}

<<expression_comparison, fig.keep="all", echo=FALSE, message=F, warning=F>>=
  source( paste( working_dir, "expression_comparison.R", sep="/"))
@

\section{Interaction numbers report}

<<interaction_numbers, fig.keep="all", echo=FALSE, message=F, warning=F>>=
  source( paste( working_dir, "interaction_numbers.R", sep="/"))
@

%' \section{Interaction scores report}
%' 
%' <<interaction_scores, fig.keep="all", echo=FALSE, message=F, warning=F>>=
%'   source( paste( working_dir, "interaction_scores.R", sep="/"))
%' @


\section{Interactions with co-presence report}

<<expression_tissues, fig.keep="all", echo=FALSE, message=F, warning=F>>=
  source( paste( working_dir, "expression_tissues.R", sep="/"))
@


\section{Interaction partners report}

<<interaction_partners, fig.keep="all", echo=FALSE, message=F, warning=F>>=
  source( paste( working_dir, "interaction_partners.R", sep="/"))
@



\end{document}

