
\documentclass{article}

\begin{document}

Here is my first \TeX\ sentence.

\begin{itemize}
  \item I was the one who typeset it!
\end{itemize}

\begin{enumerate}
  \item I was the one who typeset it!
  \item I was the one who typeset it!
\end{enumerate}

%this is a comment

%next are characters one shouldn't use: \, {, }, %, &, ~, $, ??, #, and have to be escaped using \ 
Congratulations! You received a grade of 100\% on your latest
You owe me \$10.00 and it???s about time you sent it to me!\\ %making a new line


%One can use \ after a control word for Latex to understand when control word ends, such as in \TeX\



% par is short for paragraph
Line one without paragraph
\par\ Line two with paragraph\\
%& but making tab with  also works

\textbf{making things bold}

\sf Example of changing to Sans Serif font\\\\\\

%note that font change is permanent


\leftline{Im over on the left.}

\centerline{Im in the centre.}

\rightline{Im on the right.}

{
\hsize = 4 in
\parindent = 0 pt
\leftskip = 0.5 in
\emph{one should right temporary changes within brackets}
\par
}




\section{SECTION}
\subsection{SUBSECTION1}
subsection 1 text
\subsection{SUBSECTION2}
subsection 2 text
\section{SECTION 2}
text under section 2
\subsection*{unnumbered subsection}
This subsection does not have number because I used * character

\end{document}